sass-lint:
  enabled: false

coffeescript:
  enabled: false

jshint:
  enabled: false

haml:
  enabled: false
  config_file: .haml-lint.yml

rubocop:
  version: 1.22.1
  config_file: .rubocop.yml
