require: 
  - rt_rubocop_defaults
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'config/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Rails/InverseOf:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'db/**/*'

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/Encoding:
  Enabled: false