version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: .docker/ruby/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && rdebug-ide --skip_wait_for_start --host 0.0.0.0 --port 1234 --dispatcher-port 26162 -- bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
      - redis
    environment:
      - SPROCKETS_CACHE=/cache
      - DATABASE_URL=postgres://postgres:justask@postgres/justask_development?pool=25
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
      - cache:/cache
    ports:
      - 3000:3000
      - 1234:1234

  redis:
    image: redis:6.2.10-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:10.12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: justask
      POSTGRES_DB: justask_development
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  cache:
