---
- Are you:
  - afraid of:
    - going outside at night
    - the dark
  - religious

- Can you:
  - cook
  - dance
  - draw
  - play:
    - any:
      - sports
    - baseball
    - the:
      - guitar
      - piano
      - saxophone
      - trumpet
  - ski
  - speak a foreign language
  - swim
  - yodel

- Do:
  - you:
    - have:
      - a nickname
      - any:
        - siblings
        - pets
    - like:
      - muffins
      - social networks
      - the place where you live
      - to:
        - travel
        - sing out loud when no one else is around
      - video games
    - prefer to:
      - browse the Internet on your phone, computer, or another device
      - live in a house or a flat
      - take baths or showers
      - watch movies or read books
    - recycle
    - think that late is better than never
    - want:
      - more:
        - friends
        - money
        - things than you need
      - old times back
      - to know more:
        - about:
          - history
          - new inventions
          - your:
            - future
            - relatives
  - your:
    - friends:
      - know:
        - [much, too much]:
          - about:
            - you
            - your:
              - family
              - friends
              - hobbies
              - life
      - like:
        - muffins
        - social networks
        - video games
        - you the way you are

- Have you ever:
  - been:
    - caught:
      - cheating
      - doing things you shouldn't do
    - mistaken for someone else
    - to:
      - Australia
      - Austria
      - Brazil
      - Bulgaria
      - China
      - Czechia
      - Finland
      - France
      - Germany
      - Italy
      - Japan
      - Mexico
      - Monaco
      - Norway
      - Poland
      - Russia
      - Slovakia
      - Slovenia
      - Sweden
      - Switzerland
      - Ukraine
      - Venezuela
      - the:
        - USA
        - United Kingdom
  - had an accident
  - listened to:
    - classical music
    - drum and bass
    - dubstep
    - frenchcore
    - hardstyle
    - J-Pop
    - K-Pop
    - metal
    - music:
      - "from the 50's"
      - "from the 60's"
      - "from the 70's"
      - "from the 80's"
      - "from the 90's"
    - nightcore
    - punk rock
    - trance
    - vaporwave
  - pet:
    - a bat
    - a bnuuy
    - a bunny
    - a cat
    - a coyote
    - a dog
    - a dragon
    - a ferret
    - a fox
    - a horse
    - a hyena
    - a lion
    - a lizard
    - a marten
    - a mouse
    - a raccoon
    - a rat
    - a shark
    - a wolf
    - an opossum
    - an otter
    - an owl
  - ridden a horse
  - written:
    - a love letter
    - code
    - in Japanese

- How:
  - fast:
    - are you
    - is your internet connection
  - has your day been
  - often do you:
    - cook
    - eat food not prepared by yourself
    - iron your clothes
    - take selfies
    - use condiments
  - many:
    - followers is too many
    - open tabs do you currently have
  - old are you

- What:
  - [activity, activities]:
    - do you enjoy the most
  - apps do you use daily
  - do you:
    - do:
      - for a living
      - for fun
      - on the weekend
    - like more,:
      - dogs or cats
      - shower or bath
      - tea or coffee
    - think about:
      - Bad Dragon
      - cats
      - coyotes
      - dogs
      - dragons
      - '"fact" accounts'
      - foxes
      - lizards
      - raccoons
      - society
      - surveillance
      - the Internet
    - usually:
      - do when you're bored
      - have for breakfast
  - habit do you really find cute in a person
  - is:
    - "heavier: a kilogram of steel, or a kilogram of feathers"
    - one thing you would like to become better at
    - the:
      - [best, worst]:
        - fast food chain
        - thing:
          - about:
              - society
              - the Internet
              - your:
                - country
                - favourite:
                  - book
                  - movie
                  - series
                - hometown
          - ever
          - one can do if they're bored
        - way to prepare and eat eggs
    - your:
      - dream job
      - favourite:
        - activity
        - animal
        - beverage
        - board game
        - book series
        - console
        - food
        - Internet browser
        - language
        - name
        - number
        - piece of music
        - programming language
        - season
        - snack
        - sports team
        - text editor
        - type of cheese
        - video game
        - way to eat a potato
        - website
      - first memory
  - kind of animals do you have
  - languages do you know
  - was:
    - the:
      - best day of your life like
      - [best, worst]:
        - thing you've eaten so far
      - last:
          - concert you've been to
          - song you listened to on repeat
          - thing you:
            - ate
            - bought
            - did
            - looked for
    - your favourite song:
      - as a kid
      - from a few weeks ago
  - would you do if you:
    - had:
        - one billion euros
        - one million euros
        - the ability to fly
    - were a dragon
    - woke up with:
      - some drawings in your face
      - someone else next to you

- Which food do you:
  - hate
  - love

- Who is:
  - the most famous person you have met
  - your favourite:
    - Retrospring user
    - actor
    - artist
    - comedian
    - musician

- Why do:
  - people climb mountains
  - printers never work when you need them
  - they call it oven when you of in the cold food of out hot eat the food

- Would you:
  - buy a cheese flavoured bubble gum
  - eat a cactus
  - rather:
    - be the best player on a horrible team or the worst player on a great team
    - live in:
      - a city or in the countryside
    - lose an arm or a leg
