import 'core-js/stable'
import 'regenerator-runtime/runtime'

import '../legacy/jquery'
import 'popper.js'
import 'bootstrap'
import 'particleground/jquery.particleground.min'
import Cookies from 'js-cookie'

# this file is generated by Rails
import I18n from '../legacy/i18n'
import '../legacy/pagination'
import '../legacy/locale-box'
import '../legacy/util'

I18n.defaultLocale = 'en';
I18n.locale = Cookies.get('hl') || 'en';

_ready = ->
  $('[data-toggle="tooltip"]').tooltip()
  $('.dropdown-toggle').dropdown()

  if document.getElementById('particles')?
    jumbo         = $ '.j2-jumbo'
    bodyColorOrig = jumbo.css 'background-color'
    bodyColor     = doppler 0.25, bodyColorOrig
    console.log bodyColor, bodyColorOrig
    particleground document.getElementById('particles'),
      dotColor: bodyColor
      lineColor: bodyColor
      density: 23000

$(document).ready _ready
$(document).on 'turbolinks:load', _ready