import '../jquery'
import 'popper.js'
import 'bootstrap'
import {} from 'jquery-ujs'
import 'jquery.turbolinks/src/jquery.turbolinks'
import 'jquery.guillotine'
import 'particleground/jquery.particleground.min'
import 'jquery.growl'

import './ban'
import './comment'
import './destroy'
import './privileges'
import './vote'